name: dbt Cloud Post-Run Git Update

# Trigger this action after the dbt Cloud job finishes
on:
  workflow_dispatch:   # This allows you to trigger the action manually or via webhook

jobs:
  git_auto_update:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Set up Git
      - name: Set up Git
        run: |
          git config --global user.name "Randy Labidou"
          git config --global user.email "labidour@gmail.com"

      # Execute the Git auto-update script
      - name: Run Git Auto-Update
        run: |
          bash ./git_auto_update.sh

      # Push changes back to the repository
      - name: Push changes
        run: |
          git push origin main
